name: Reusable workflow

on:
  workflow_call:

jobs:
  job-reusable-wf:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Waiting 10 seconds..."
          sleep 10
          echo "Hello World"