name: Test 72 # Related to https://stackoverflow.com/questions/74386773/github-actions-job-is-skipped-although-all-needs-succeeded

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment to deploy to (select either dev, qa or prod only)
        required: true
        default: dev

jobs:
  auto-versioning:
    if: github.event.inputs.environment == 'qa'
    uses: ./.github/workflows/48-reusable-workflow-2.yml

  build-test-api:
    uses: ./.github/workflows/48-reusable-workflow-2.yml
    needs: auto-versioning
    if: |
      always() &&
      (needs.auto-versioning.result == 'success' || needs.auto-versioning.result == 'skipped')

  deploy-api: #always skipped, if input parameter 'environment' is set to "dev"
    if: success('build-test-api')
    needs: build-test-api
    uses: ./.github/workflows/48-reusable-workflow-2.yml
