name: Test 72 # Related to https://stackoverflow.com/questions/74386773/github-actions-job-is-skipped-although-all-needs-succeeded

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment to deploy to (select either dev, qa or prod only)
        required: true
        default: dev

jobs:
  set-deployment-env:
    runs-on: ubuntu-latest
    outputs:
      deploy_environment: ${{ steps.deplEnv.outputs.deploy_environment }}
    steps:
      - id: deplEnv
        name: Set deployment environment
        run: |
          DEPLOY_ENVIRONMENT=$(
          if [ ! -z '${{ github.event.inputs.environment }}' ]; then
            echo '${{ github.event.inputs.environment }}'
          elif [ '${{ github.ref_name }}' == 'develop' ]; then
            echo 'dev'
          else
            echo "::error ::Failed to determine deployment environment. Cancelling deployment ..."
            exit 1
          fi
          )
          echo "Deploying on $DEPLOY_ENVIRONMENT"
          echo "::set-output name=deploy_environment::$DEPLOY_ENVIRONMENT"

  auto-versioning:
    needs: set-deployment-env
    if: needs.set-deployment-env.outputs.deploy_environment == 'qa'
    uses: ./.github/workflows/48-reusable-workflow-2.yml

  build-test-api:
    uses: ./.github/workflows/48-reusable-workflow-2.yml
    needs: [set-deployment-env, auto-versioning]
    if: |
      always() &&
      (needs.set-deployment-env.result == 'success') &&
      (needs.auto-versioning.result == 'success' || needs.auto-versioning.result == 'skipped')

  terraform-plan:
    uses: ./.github/workflows/48-reusable-workflow-2.yml
    needs: set-deployment-env

  terraform-apply:
    needs: [terraform-plan]
    uses: ./.github/workflows/48-reusable-workflow-2.yml

  build-test-ui:
    needs: [terraform-apply]
    uses: ./.github/workflows/48-reusable-workflow-2.yml

  deploy-api: #always skipped, if input parameter 'environment' is set to "dev"
    needs: [build-test-api, terraform-apply]
    uses: ./.github/workflows/48-reusable-workflow-2.yml
